name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t ytdl-apk .

      - name: Run Docker container & extract APK
        run: |
          docker run --rm -v ${{ github.workspace }}:/app ytdl-apk
          cp bin/*.apk .

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: yt-downloader-apk
          path: "*.apk"
